"""Generate per-client docker-compose services from the client registry.

This is the payoff of the *soft isolation* design: any client flipped to
``isolation: container`` in the registry graduates from "a profile inside the
shared gateway container" to "its own container" — with no data migration,
because the container simply mounts that client's existing profile directory
(``<data_root>/profiles/<name>``) as its data root.

The generated compose follows the repo's conventions (see docker-compose.yml):
image ``hermes-agent``, ``network_mode: host``, ``HERMES_UID/GID`` passthrough,
``command: ["gateway", "run"]``. Each service additionally pulls the client's
Telegram token from its host-side secret env file.

This emits a *reviewable starting point*, not a guaranteed-correct runtime —
verify it against your deployment before `docker compose up`. In particular:

* **Exclude isolated clients from the shared gateway.** A client that gets its
  own container must NOT also be run by the shared prod gateway, or it runs
  twice. Keep isolated clients out of the shared container's volume/profile
  set (e.g. give them a dedicated ``profiles/`` subtree or an allowlist).
* **network_mode: host** matches the repo default and is fine for outbound
  Telegram long-polling, but two services that both bind a port (API server,
  dashboard) would clash on host networking. Override with ``--network`` if
  you enable those.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except Exception:  # pragma: no cover
    yaml = None  # type: ignore[assignment]

from hermes_cli.clients import Client, Registry, load_registry

_HEADER = """\
# GENERATED by `python -m hermes_cli.compose_gen` from the client registry.
# Do not edit by hand — re-run the generator after changing clients.yaml.
#
# One service per client with `isolation: container`. Each mounts its own
# profile dir as the data root (no data migration from the shared layout)
# and reads its Telegram token from a host-side secret env file.
#
# Bring up with:  docker compose -f {filename} up -d
# IMPORTANT: isolated clients must be excluded from the shared gateway
# container so they don't run twice. See hermes_cli/compose_gen.py.
"""


def host_profile_path(client: Client, data_root: str) -> str:
    """Host path to the client's data root for the isolated container."""
    root = Path(data_root)
    if client.is_default:
        return str(root)
    return str(root / "profiles" / client.profile)


def build_service(
    client: Client,
    *,
    data_root: str,
    image: str = "hermes-agent",
    network_mode: str = "host",
    container_data_dir: str = "/opt/data",
) -> dict[str, Any]:
    """Build the compose service mapping for one isolated client."""
    service: dict[str, Any] = {
        "image": image,
        "container_name": f"hermes-{client.name}",
        "restart": "unless-stopped",
        "network_mode": network_mode,
        "volumes": [f"{host_profile_path(client, data_root)}:{container_data_dir}"],
        "environment": [
            "HERMES_UID=${HERMES_UID:-10000}",
            "HERMES_GID=${HERMES_GID:-10000}",
        ],
        "command": ["gateway", "run"],
    }
    if client.telegram_token_ref:
        # env_file is read from the host at compose time; keep secrets out of
        # the generated yaml itself.
        service["env_file"] = [f"{data_root}/secrets/{client.name}.env"]
    return service


def isolated_clients(registry: Registry, env: str | None = None) -> tuple[Client, ...]:
    """Clients marked ``isolation: container`` (optionally filtered by env)."""
    return tuple(
        c for c in registry.clients
        if c.isolation == "container" and (env is None or c.env == env)
    )


def isolated_profile_names(registry: Registry, env: str | None = None) -> tuple[str, ...]:
    """Profile names for clients marked ``isolation: container``.

    This is the *exclusion set* the shared gateway must honor: a client that
    gets its own container (this list) must NOT also be seeded/started by the
    shared prod gateway, or it runs twice (Telegram 409). The boot hook
    (``docker/cont-init.d/04-registry-gate``) reads the artifact produced from
    this list (``<data_root>/isolated.list``) so the compose file and the boot
    reconcile can't disagree about who is isolated.

    Returns profile names (the on-disk directory under ``profiles/<name>/`` and
    the s6 ``gateway-<name>`` slot key), de-duplicated and in file order.
    """
    seen: set[str] = set()
    names: list[str] = []
    for c in isolated_clients(registry, env):
        if c.profile not in seen:
            seen.add(c.profile)
            names.append(c.profile)
    return tuple(names)


def render_isolated_list(registry: Registry, env: str | None = None) -> str:
    """Render the ``isolated.list`` artifact: one profile name per line.

    A trailing newline is always emitted (empty file == no isolated clients),
    so the boot hook can read it line-by-line without special-casing EOF.
    """
    names = isolated_profile_names(registry, env)
    return "".join(f"{name}\n" for name in names)


def generate_compose(
    registry: Registry,
    *,
    env: str | None = None,
    data_root: str = "/opt/data-prod",
    image: str = "hermes-agent",
    network_mode: str = "host",
) -> dict[str, Any]:
    """Build the full compose document for all isolated clients."""
    services = {
        f"hermes-{c.name}": build_service(
            c, data_root=data_root, image=image, network_mode=network_mode,
        )
        for c in isolated_clients(registry, env)
    }
    return {"services": services}


def render(compose: dict[str, Any], *, filename: str = "docker-compose.clients.yml") -> str:
    """Render the compose document to YAML with the explanatory header."""
    if yaml is None:  # pragma: no cover
        raise RuntimeError("PyYAML is required to render compose output")
    header = _HEADER.format(filename=filename)
    body = yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    return header + "\n" + body


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="hermes-compose-gen",
        description="Generate per-client docker-compose services for isolated clients.",
    )
    parser.add_argument("--registry", help="path to clients.yaml (default: $HERMES_CLIENTS_REGISTRY)")
    parser.add_argument("--env", choices=["prod", "dev"], help="only this environment")
    parser.add_argument("--data-root", default="/opt/data-prod",
                        help="host data volume the isolated profiles live under")
    parser.add_argument("--image", default="hermes-agent")
    parser.add_argument("--network", default="host", help="docker network_mode for each service")
    parser.add_argument("--output", "-o", help="write to this file (default: stdout)")
    args = parser.parse_args(argv)

    try:
        registry = load_registry(args.registry)
        compose = generate_compose(
            registry, env=args.env, data_root=args.data_root,
            image=args.image, network_mode=args.network,
        )
        filename = args.output or "docker-compose.clients.yml"
        text = render(compose, filename=Path(filename).name)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if not compose["services"]:
        print(
            "# no clients have isolation: container — nothing to generate.",
            file=sys.stderr,
        )

    if args.output:
        Path(args.output).write_text(text, encoding="utf-8")
        print(f"wrote {len(compose['services'])} service(s) to {args.output}", file=sys.stderr)
        # Also emit the exclusion artifact next to the compose file's data root
        # so the boot hook (04-registry-gate) and this compose file can't
        # disagree about which profiles are isolated (and must be kept OUT of
        # the shared gateway). Writing it here keeps a single source of truth:
        # whoever regenerates the compose regenerates the exclusion list.
        isolated_list_path = Path(args.data_root) / "isolated.list"
        try:
            isolated_list_path.write_text(
                render_isolated_list(registry, env=args.env), encoding="utf-8"
            )
            print(
                f"wrote {len(isolated_profile_names(registry, env=args.env))} "
                f"isolated profile(s) to {isolated_list_path}",
                file=sys.stderr,
            )
        except OSError as exc:
            # Non-fatal: the compose file is still valid. The boot hook treats a
            # missing isolated.list as "nothing isolated" (today's behavior).
            print(f"warning: could not write {isolated_list_path}: {exc}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
